apiVersion: v1
kind: PersistentVolume
metadata:
 name: wspv
spec:
 storageClassName: oci-fss
 capacity:
  storage: 5Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: 10.0.10.5
  path: "/filesystem-oke"
  readOnly: false
