kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wspvc
spec:
  storageClassName: oci-fss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: wspv
