apiVersion: v1
kind: Pod
metadata:
  labels:
    app: opc_wp
  name: opc_wp
spec:
  containers:
  - name: wordpress
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: WORDPRESS_DB_PASSWORD
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_HOST
      value: db:3306
    - name: APACHE_CONFDIR
      value: /etc/apache2
    - name: APACHE_ENVVARS
      value: /etc/apache2/envvars
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: HOSTNAME
    image: docker.io/library/wordpress:latest
    name: opcwordpress1
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    - containerPort: 3306
      hostPort: 3306
      protocol: TCP
    securityContext:
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      seLinuxOptions: 
        type: spc_t
    volumeMounts:
    - mountPath: /var/www/html
      name: home-opc-wordpress
      workingDir: /var/www/html
  volumes:
  - name: home-opc-wordpress
    hostPath:
      path: /home/opc/wordpress
      type: Directory
